# Generated by Django 5.2.8 on 2025-11-18 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jenis', models.CharField(choices=[('PENEBARAN', 'Penebaran benur'), ('PANEN', 'Panen'), ('DARI_TAMBAK', 'Batch dibuat di tambak'), ('UJI_LAB', 'Uji laboratorium'), ('SIAP_EKSPOR', 'Disiapkan untuk ekspor'), ('DIEKSPOR', 'Diekspor'), ('DITERIMA', 'Diterima pihak tujuan'), ('LAINNYA', 'Lainnya')], max_length=20)),
                ('lokasi', models.CharField(max_length=200)),
                ('pelaku', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tanggal', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('default_batas_aman_cs137', models.FloatField(blank=True, help_text='Batas aman Cs-137 (Bq/kg) untuk komoditas ini', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestBatch',
            fields=[
                ('kode_batch', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('tanggal_tebar', models.DateField()),
                ('tanggal_panen', models.DateField()),
                ('volume_kg', models.FloatField()),
                ('tujuan', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quality_status', models.CharField(choices=[('AMAN', 'Aman'), ('PENDING', 'Dalam Pengecekan'), ('MASALAH', 'Bermasalah')], default='PENDING', max_length=20)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('is_shipped', models.BooleanField(default=False)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='batches.commodity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
