# Generated by Django 5.2.8 on 2025-11-18 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'user__role': 'farmOwner'}, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='profiles.userprofile'),
        ),
    ]
