# Generated by Django 5.2.8 on 2025-11-18 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.city')),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_cs137', models.FloatField()),
                ('kesimpulan', models.CharField(help_text='AMAN / BERMASALAH', max_length=20)),
                ('tanggal_uji', models.DateField()),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test', to='batches.harvestbatch')),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='labs.laboratory')),
            ],
            options={
                'ordering': ['tanggal_uji'],
            },
        ),
    ]
