# Generated by Django 5.2.8 on 2025-11-15 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='qc',
            field=models.ForeignKey(limit_choices_to={'user__role': 'labAssistant'}, on_delete=django.db.models.deletion.PROTECT, to='profiles.userprofile'),
        ),
    ]
