# Generated by Django 5.2.3 on 2025-11-18 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='labs.laboratory'),
        ),
    ]
